### ISSUE TITLE
i18n and i10

### ISSUE THREAD

**Issue by gedw99** [gobuffalo/plush#1]
wondering if plush should support some of the localisation features people need ?

Maybe it should not go into Plush, but rather before it at the users golang app level ?

Example:
- language
- currency
- datatime

There are some good golang libs that make a good job of this now.
I think this holds the best promise right now: https://github.com/vube/i18n

then there is the workflow for managing a project where you need EN and then other languages.

curious what your think as your closer to this than me.

**Comment by stanislas-m** [comment]
> Maybe it should not go into Plush, but rather before it at the users golang app level ?

It's supported by Buffalo now. It makes sense to use i18n inside the whole app, not just in the templates. :)

I'm closing the issue, but if you find something laking in the current i18n support in Buffalo, please feel free to open an issue there: https://github.com/gobuffalo/buffalo/issues

**Comment by gedw99** [comment]
@stanislas-m thanks for the follow up about this. Very much appreciated.
