### ISSUE TITLE
`if (var1 = var2)` does not error

### ISSUE THREAD

**Issue by soypat** [gobuffalo/plush#115]
Above syntax can be a headache to correct since it looks OK at a glance

**Comment by Mido-sys** [comment]
More syntrax issues:

1. `if ({}) `
2. `if (x-6) `
3. `if (x + 6)` 

This [pull request](https://github.com/gobuffalo/plush/pull/128) should fix the above.

**Comment by paganotoni** [comment]
Fixed with #128, thanks @Mido-sys
