### ISSUE TITLE
Can't output typed string

### ISSUE THREAD

**Issue by dionysius** [gobuffalo/plush#117]
i have a type which is based on string:

```
type UUID string
```

Which is used in a struct

```
type Something {
   ID UUID
}
```

when trying to output that in the template, no output is printed:
```
<%= something.ID %>
```

Please advice if I can tell plush to typecast to string or is there a fmt.Printf equivalent?

**Comment by dionysius** [comment]
Workaround is defining a helper function and using fmt.Sprintf to force a string output of any type:

```diff
diff --git a/actions/render.go b/actions/render.go
--- a/actions/render.go
+++ b/actions/render.go
@@ -1,6 +1,8 @@
 package actions
 
 import (
+       "fmt"
+
        "github.com/gobuffalo/buffalo/render"
        "github.com/gobuffalo/packr/v2"
 )
@@ -24,6 +26,11 @@ func init() {
                        // forms.FormKey:     forms.Form,
                        // forms.FormForKey:  forms.FormFor,
+                       "out":                 out,
                },
        })
 }
+
+func out(v interface{}) string {
+       return fmt.Sprintf("%v", v)
+}
```

and use that function in the template, e.g.
```html
<td><%= out(something.ID) %></td>
```

**Comment by ddouglas** [comment]
Have you tried implementing the `Stringer` interface and defining a `String() string` func on the `type UUID string`? Even if it is not automatically called you can still call it from within the template.

**Comment by dionysius** [comment]
I could've done that. The [workaround](https://github.com/gobuffalo/plush/issues/117#issuecomment-742669818) had served me well also for types from external packages where I had no control of its implementation.
