### ISSUE TITLE
 “continue” statements in if clauses within for loops

### ISSUE THREAD

**Issue by beatscode** [gobuffalo/plush#12]
does plush allow “continue” statements in if clauses within for loops?
```
<%= for(i, arg) in Args { %>
                <%= if ( arg.Name == “created_at” ) { %>
                     <%= continue %> asdfg
               <% } %>
                <%=arg.Name%>, _ := params.Args[“<%=arg.Name%>“].(string)
            <% } %>
```
after rendering the template. the "asdfs" after continue is rendered. and also everything after that line for that matter. I tried `<%= continue %>` and  `<% continue %>`

**Comment by markbates** [comment]
Not currently it doesn’t. However, i would love to see a PR for it. :)

**Comment by beatscode** [comment]
I'll take a look. thanks

**Comment by mkungla** [comment]
That's so needed feature

**Comment by paganotoni** [comment]
Added on v4.1.4
