### ISSUE TITLE
plush DefaultTimeFormat not working in plush/v4 

### ISSUE THREAD

**Issue by mogensen** [gobuffalo/plush#121]
Hi,

In the earlier versions of plush i have been using the following to set the default formatting for dates in my web applications. 

```golang
plush.DefaultTimeFormat = "02 Jan 2006"
```

But in the resent release `github.com/gobuffalo/plush/v4` this is no longer working.
I am using plush from buffalo (version v0.16.21).

I have tried setting the DefaultTimeFormat in the `func App() *buffalo.App` function and in a `buffalo.MiddlewareFunc`. Non of these seems to work as expected.

Has this feature been deprecated or am I missing something?

**Comment by Mido-sys** [comment]
@mogensen, you could set  the `TIME_FORMAT` in the context. 
```
ctx.Set("TIME_FORMAT", "02 Jan 2006")
s, err = Render(input, ctx)
```

**Comment by paganotoni** [comment]
This is an interesting one. I wonder what could have changed that broke it. 🤔

**Comment by Mido-sys** [comment]
@paganotoni , No changes since [2018](https://github.com/gobuffalo/plush/commit/bac5312890be30a003f7dc4e20b94b65a514c861#diff-1d0ff0ed2d20ca4a373e5ced204262a960b1e9c7a545e7ea9dc38944ed89c1ef).

**Comment by paganotoni** [comment]
In that case given TIME_FORMAT solves it lets close this issue.
