### ISSUE TITLE
Docs for using outside of gobuffalo?

### ISSUE THREAD

**Issue by zhammer** [gobuffalo/plush#122]
Hi! I’ve used plush in a buffalo app and really enjoyed using it. I’m now looking to plug plush into a non-buffalo app and would appreciate a reference implementation of, say, plush in a vanilla http.ServeMux app.

thanks!

**Comment by paganotoni** [comment]
hey @zhammer! Thats a good question. I recently put [this repo](https://github.com/paganotoni/plgo) together. Hoping it clarifies things. let me know if it works for you. Will write something soon.

**Comment by paganotoni** [comment]
https://wawand.co/blog/posts/using-plush-with-go-946e0922-d6bf-4c3f-9e22-b60b104053aa/
