### ISSUE TITLE
If condition with array or map index

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/plush#132]
Seems the following expression no longer works with the version we have on `master`:

```
 <%= if( flash["error"]) { %>
```

If crashes saying:

```
auth/login.plush.html: line 17: syntax error: invalid if condition, got (flash["error"])
```

cc @Mido-sys

**Comment by Mido-sys** [comment]
@paganotoni , I pushed a fix to allow array or map index in if condition.

**Comment by paganotoni** [comment]
Solved. Thanks!
