### ISSUE TITLE
Chaining function result ends in error

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/plush#139]
Similar to the arrays issue when trying to call a member of the result of a function call plush errors.

Code:
```
...
<p class="mr-2">
    Employees will be reminded on 
    <date class="font-semibold">
        <%= period.EmployeeReviewReminderDate().Format("Jan 2, 2006") %>
    </date>.
</p>
...
```

Error:

```
no prefix parse function for DOT found
```

It would be good to support this.

cc @Mido-sys

**Comment by Mido-sys** [comment]
@paganotoni sounds good. Thanks for creating the issue. I will probably get it done sometime next week.

**Comment by paganotoni** [comment]
Awesome. No rush on this. Appreciate all the great work you're putting into plush.

**Comment by Mido-sys** [comment]
@paganotoni, Sorry, I've been swamped lately. However, I will try to get it done before the end of the month.

**Comment by paganotoni** [comment]
Hey! don't worry about that. I appreciate your effort with all these issues and understand you take your time. Thanks in advance for all your dedication.

**Comment by dazhoudotnet** [comment]
Can this feature be used?

**Comment by paganotoni** [comment]
@temuera agree. It would be awesome to have this one solved cc @Mido-sys .

**Comment by paganotoni** [comment]
@temuera At the moment I use variables as a workaround.

```
<p class="mr-2">
    Employees will be reminded on 
    <date class="font-semibold">
        <% let date = period.EmployeeReviewReminderDate() %>
        <%= date.Format("Jan 2, 2006") %>
    </date>.
</p>
...

**Comment by Mido-sys** [comment]
@paganotoni 

Hello Antonio, It's been a long time. I know I promised to get this done back in 2021, so my apologies for going dark on this for 3 years now.  I sent a PR https://github.com/gobuffalo/plush/pull/181 and added different test cases. Please let me know if you think a test case is missing. 

 I also fixed a bug that plush didn't return an error when undefined function is called on an object.

**Comment by paganotoni** [comment]
Hey @Mido-sys! Thanks a lot!
