### ISSUE TITLE
Can't evaluate if conditions properly with an undefined variable

### ISSUE THREAD

**Issue by Mido-sys** [gobuffalo/plush#157]
Plush evaluates undefined variables in if conditions without throwing an error; however, it becomes an issue with this example. 

```
	r := require.New(t)
	type page struct {
		PageTitle string
	}
	g := &page{"cafe"}
	ctx := NewContext()
	ctx.Set("pages", g)
	ctx.Set("path", "home")

	input := `<%= if ( path != "pagePath" || (page && page.PageTitle != "cafe") ) { %>hi<%} %>`

	s, err := Render(input, ctx)
	r.NoError(err)
	r.Equal("hi", s)

```
Currently, this should return "hi" as one of the conditions `path != "pagePath"` is true; however, it returns an empty string because the if condition values on the right of the `or` return an error, so it bubbles back up and results in evaluating the condition as false. 

This behaviour is inconsistent  because this condition evaluates as true `<%= if ( path != "pagePath" || !page) { %>hi<%} %>`

**Comment by mattbnz** [comment]
I've hit this issue too so I'd like this to remain open rather than be auto-closed as stale. It's definitely a pain-point with plush.

**Comment by sio4** [comment]
> I've hit this issue too so I'd like this to remain open rather than be auto-closed as stale. It's definitely a pain-point with plush.

Sure, absolutely! I configured auto close action across all modules to make it easy to maintain, but if any issue is still meaningful, it should remain as open. The main purpose of this autoclose action is actually not to close issues but make it possible to get an insight into the issue. Also, the more information gathered, the better the solution will be.

**Comment by Mido-sys** [comment]
@sio4, I pushed a fix for this. 

Thanks, @mattbnz, for the reminder.

**Comment by sio4** [comment]
> @sio4, I pushed a fix for this. 
> 
> Thanks, @mattbnz, for the reminder. 

Thank! Will check!

**Comment by Mido-sys** [comment]
I pushed an improved version. I realized my first commit would have ignored syntax errors and returned true if one of the nodes was true. I also added more tests.
