### ISSUE TITLE
Better Helper Errors

### ISSUE THREAD

**Issue by gose** [gobuffalo/plush#17]
If you pass a non-existent param into a Helper, you will get:

`<nil> (<nil>) is an invalid value - evalCallExpression`

This issue is to track enhancing this behavior to output more descriptive details around where the error is occuring.

**Comment by markbates** [comment]
Can you please give me a working example that returns this result? I've tried a few attempts at recreating, and can't. Thanks.

**Comment by markbates** [comment]
Also, that error message doesn't appear in the code base, which makes me think you might be running an old version of plush.

**Comment by markbates** [comment]
I'm closing this issue for now, since I believe it is due to an out of date version of plush. Please re-test with the latest version. If it's still an error please re-open this ticket with an example that can recreate the issue. Thanks.

**Comment by gose** [comment]
Here's what `0.9.5` output looks like:

In `actions/render.go` I add a Helper like:

    "NumberWithDelimiter": func(n int) string {
        return humanize.Comma(int64(n))
    },

Then in a template, I mis-call the helper:

    <%= NumberWithDelimiter(undefinedArg) %>

Which yields the following error:

    <nil> (<nil>) is an invalid value - evalCallExpression 
    github.com/markbates/pop.(*Connection).Transaction.func1
    /Users/gose/go/src/github.com/markbates/pop/connection.go:116
    github.com/markbates/pop.(*postgresql).Lock
    /Users/gose/go/src/github.com/markbates/pop/postgresql.go:157
    github.com/markbates/pop.(*Connection).Transaction

**Comment by markbates** [comment]
interesting though, while that error message has been fixed, it did uncover another issue. the code sample you provided, doesn’t actually raise an error any more, which is should.
so there is a bug there, just not the one you thought. :slightly_smiling_face:
