### ISSUE TITLE
bug: Division by zero causes Plush to panic.

### ISSUE THREAD

**Issue by Mido-sys** [gobuffalo/plush#182]
### Description

Plush Panics and throws an error when dividing the numerator with zero

### To Reproduce

``` 10 / 0``` results in ```panic: runtime error: integer divide by zero```dividing

### Additional Context

Details

<details>

```
Paste the output of `buffalo info` here!
```

</details>

**Comment by Mido-sys** [comment]
Hello @paganotoni, I sent a PR to fix the following issue.

**Comment by paganotoni** [comment]
Thank you @Mido-sys
