### ISSUE TITLE
bug: Avoid the overhead cost of WriteString in write function in compiler.go

### ISSUE THREAD

**Issue by Mido-sys** [gobuffalo/plush#188]
### Description

The [WriteString()](https://github.com/gobuffalo/plush/blob/main/compiler.go#L79) causes an overhead as the underlying bytes change. We know that the string value for each WriteString line of code won't change so we can include use `unsafe. pointer` which will result in zero allocation. 

### Additional Context

Details

<details>

```
Paste the output of `buffalo info` here!
```

</details>

**Comment by paganotoni** [comment]
Thanks @Mido-sys, Is there a way to benchmark this one? I would love to understand the impact of it better. A test of benchmark would be appreciated.

**Comment by Mido-sys** [comment]
Before the fix, this was result from pprof
![Screenshot from 2024-08-06 06-08-40](https://github.com/user-attachments/assets/4351c55d-6e35-4dbb-8725-c5c8ed805100)

After applying the fix, plushRender didn't appear

**Comment by Mido-sys** [comment]
Also, due to go.mod is 1.13 we couldn't use the recommended way of using unsafe which was introduced in 1.17
`unsafe.Slice(unsafe.StringData(s), len(s)) `


So I got the function from here https://stackoverflow.com/a/59210739

**Comment by paganotoni** [comment]
ok. Good. Its time to cut a v5 for plush, with some breaking changes. one of those is reduce the dependencies that the helpers bring in. Once we do that we can change it to the recommended way of doing it. Thanks @Mido-sys !

**Comment by Mido-sys** [comment]
Also with Go1.22 we can use this [[]byte("STRING")](https://github.com/kubernetes/kubernetes/issues/124656)

**Comment by paganotoni** [comment]
@Mido-sys I just tagged v5 with Go 1.21.

**Comment by Mido-sys** [comment]
@paganotoni  I upgraded the function.

**Comment by ouamer-dahmani** [comment]
@Mido-sys 
See this comment: https://github.com/kubernetes/kubernetes/issues/124656#issuecomment-2327677824

String-to-byte conversion should still trigger allocations. I believe you are victim of a bad benchmark.
