### ISSUE TITLE
Parse error on variable names with numbers

### ISSUE THREAD

**Issue by nzoschke** [gobuffalo/plush#2]
I tried this template in a <script> tag:

`counts["2XX"] = <%= json(count2XX) %>;`

The page returns a 500, with an error trace beginning with:

```
expected next token to be ), got INT instead
no prefix parse function for ) found
error inside of calling function
```

Renaming the variable to letters only like `countSuccess` works as expected.

**Comment by markbates** [comment]
This should be fixed with this commit https://github.com/gobuffalo/plush/commit/dacd21b2b4b4a5fe0806bd6cd5397d48000eb9a4
