### ISSUE TITLE
access session variable from helper func

### ISSUE THREAD

**Issue by mbetel** [gobuffalo/plush#27]
Is there a way to get access to the session variables in a helper function? Or am I overlooking something dumb? :)

**Comment by markbates** [comment]
You can access the session in a template using the `session` variable. `<%= session.Get(“foo”) %>`

**Comment by mbetel** [comment]
Thanx thats good to know, but what I meant was accessing them via the plush.HelperContext without exposing them to the user,  Is that possible?

**Comment by markbates** [comment]
Everything that’s in the context is available in the HelperContext. help.Value(“session”).(*buffalo.Session) don’t quote me on the casting there. I can’t remember the exact type right now.
