### ISSUE TITLE
Plush concurrent map panic

### ISSUE THREAD

**Issue by bketelsen** [gobuffalo/plush#4]
Gophercon site in prodution:

<details>
Apr 24 11:55:57 gopheracademy bash[6512]: fatal error: concurrent map iteration and map write
Apr 24 11:55:57 gopheracademy bash[6512]: goroutine 24049 [running]:
Apr 24 11:55:57 gopheracademy bash[6512]: runtime.throw(0xbe6290, 0x26)
Apr 24 11:55:57 gopheracademy bash[6512]:         /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42063ef70 sp=0xc42063ef50
Apr 24 11:55:57 gopheracademy bash[6512]: runtime.mapiternext(0xc42063f080)
Apr 24 11:55:57 gopheracademy bash[6512]:         /usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc42063f020 sp=0xc42063ef70
Apr 24 11:55:57 gopheracademy bash[6512]: github.com/gobuffalo/plush.(*Template).Exec(0xc4205690e0, 0xc420250e40, 0xc420250e70, 0x0, 0xc420250e70, 0xc42091d800)
Apr 24 11:55:57 gopheracademy bash[6512]:         /root/go/src/github.com/gobuffalo/plush/template.go:61 +0x1f2 fp=0xc42063f0f0 sp=0xc42063f020
Apr 24 11:55:57 gopheracademy bash[6512]: github.com/gobuffalo/plush.BuffaloRenderer(0xc42091d800, 0x17fd, 0xc420768f30, 0xc420250e10, 0xc42091d800, 0x17fd, 0x9, 0xc420726000)
Apr 24 11:55:57 gopheracademy bash[6512]:         /root/go/src/github.com/gobuffalo/plush/plush.go:23 +0x178 fp=0xc42063f150 sp=0xc42063f0f0
Apr 24 11:55:57 gopheracademy bash[6512]: github.com/gobuffalo/buffalo/render.templateRenderer.exec(0xc420200280, 0xbcf902, 0x9, 0xc4204a0600, 0x2, 0x2, 0xbcf563, 0x9, 0xc420768f30, 0xc4201b5680, ...)
Apr 24 11:55:57 gopheracademy bash[6512]:         /root/go/src/github.com/gobuffalo/buffalo/render/template.go:63 +0x3b0 fp=0xc42063f2b0 sp=0xc42063f150
root@gopheracademy:~# cd go/src/github.com/gobuffalo/plush/

root@gopheracademy:~/go/src/github.com/gobuffalo/plush# git log
commit 357477abee67b4ca760dd33f7fdc032cb4241931
Author: Mark Bates <mark@markbates.com>
Date:   Tue Apr 11 11:26:49 2017 -0400

    added a truncate helper

</details>

Plush seems to be the latest revision, but I'm getting these panics many times per day now.  :(

**Comment by markbates** [comment]
What version of buffalo are you using?

**Comment by bketelsen** [comment]
0.8.0

**Comment by markbates** [comment]
Buffalo is at '0.8.1.2' I wonder if that has anything to do with it.
