### ISSUE TITLE
Rendering with backslash in template before <%=var%> fails

### ISSUE THREAD

**Issue by pvelder** [gobuffalo/plush#42]
Following unit test 

    func Test_Issue_With_Backslash(t *testing.T) {
    	r := require.New(t)
    	input := `c:\\temp\\<%=subfolder%>`
    	s, err := Render(input, NewContextWith(map[string]interface{}{
    		"subfolder": "test",
    	}))
    	r.NoError(err)
    	r.Equal(`c:\\temp\\test`, s)
    }

fails with: 

    Not equal: 
    	            	expected: "c:\\\\temp\\\\test"
    	            	received: "c:\\\\temp\\<%!=(MISSING)subfolder%!>(MISSING)"

(While the following unit test runs fine: 

    func Test_With_Slash(t *testing.T) {
    	r := require.New(t)
    	input := `c:/temp/<%=subfolder%>`
    	s, err := Render(input, NewContextWith(map[string]interface{}{
    		"subfolder": "test",
    	}))
    	r.NoError(err)
    	r.Equal(`c:/temp/test`, s)
    
)

**Comment by markbates** [comment]
A backslash before a tag is used to escape a tag so \<%= foo %> will print <%= foo %> to the screen. So that’s a feature. However, you should be able to escape that with \\. A PR for that would be welcome. 

The test passes because it uses forward slashes / not backslashes \

**Comment by markbates** [comment]
A work around would be to use a helper that produces the path you’re looking for. Or a PR to allow \\. :)

**Comment by pvelder** [comment]
Thanks Mark! Current workaround is to pass the full-path in the context.

(We'll consider doing a PR when we find some time)

**Comment by pvelder** [comment]
Wow, that was fast!  I didn't even start trying to create a fix.
Thanks Mark!

**Comment by markbates** [comment]
Don't mention it, I was in there looking at something else, and fixed it. I'll try and take a look at the map issue after lunch.

**Comment by pvelder** [comment]
Great.  But if you don't have the time. I do want to give it a try as well.  
It wil take me more time though, as I still need to finish Thorsten Ball's book :-)
