### ISSUE TITLE
failure to get struct field when having map[string]struct in context

### ISSUE THREAD

**Issue by pvelder** [gobuffalo/plush#43]
This unit test works fine: 

    type address struct {
    	Street string
    }
    
    func Test_Render_Struct_Field(t *testing.T) {
    	r := require.New(t)
    
    	input := `<p><%= a.Street %></p>`
    	s, err := Render(input, NewContextWith(map[string]interface{}{
    		"a": address{Street: "avenue des nations-unies"},
    	}))
    	r.NoError(err)
    	r.Equal(`<p>avenue des nations-unies</p>`, s)
    }

But when extending it to a map[string]address : 
    
    func Test_Render_Map_Struct_Field(t *testing.T) {
    	r := require.New(t)
    
    	input := `<p><%= a["myaddress"].Street %></p>`
    	s, err := Render(input, NewContextWith(map[string]interface{}{
    		"a": map[string]address{
    			"myaddress": address{Street: "avenue des nations-unies"},
    		},
    	}))
    	r.NoError(err)
    	r.Equal(`<p>avenue des nations-unies</p>`, s)
    }

It shows following error: 

    Received unexpected error:
		
    line 1: no prefix parse function for DOT found
    github.com/gobuffalo/plush.(*Template).Parse
        /Users/pdv/dev/src/github.com/gobuffalo/plush/template.go:41

**Comment by markbates** [comment]
Can I just say I love that you give failing, reproducible, tests. thank you!

**Comment by pvelder** [comment]
Just as a side note.  Current work around is to use an intermediate "let" assignment at the level of the map: 

    func Test_Render_Map_Struct_Field_Workaround(t *testing.T) {
    	r := require.New(t)
    
    	input := `<p><% let addr = a["myaddress"] %><%= addr.Street %></p>`
    	s, err := Render(input, NewContextWith(map[string]interface{}{
    		"a": map[string]address{
    			"myaddress": address{Street: "avenue des nations-unies"},
    		},
    	}))
    	r.NoError(err)
    	r.Equal(`<p>avenue des nations-uniesx</p>`, s)
    }

**Comment by paganotoni** [comment]
@Mido-sys do you think this one was also solved in #137?

**Comment by Mido-sys** [comment]
@paganotoni , yes :)

**Comment by paganotoni** [comment]
that's great. Thanks!. Solved in v4.1.4 with #137
