### ISSUE TITLE
Pass optional map into contentOf blocks

### ISSUE THREAD

**Issue by matryer** [gobuffalo/plush#54]
As the author of a code generation tool
I want to be able to repeat blocks of code with different context each time
So that I can dry up my templates

For example:

```
<% contentFor("greeting") { %>
    Hello, <%= person.Name %>.
<% } %>

<%=  for (person) in people { %>
    <%= contentOf("greeting", {"person":person}) %>
<% } %>
```

Discussion: https://gophers.slack.com/archives/C3MSAFD40/p1528549973000122

**Comment by stanislas-m** [comment]
Fixed with #55.
