### ISSUE TITLE
Truncate size feels weird

### ISSUE THREAD

**Issue by ruudk** [gobuffalo/plush#60]
When I tried out the `truncate` helper, it felt really weird.

I used this:
```erb
<%= truncate("Hello world!", {size: 3, trail: "[more]"}) %>
```

But the output was `[more]`

I thought the `truncate` helper had a bug.

It turns out that size is the maximum size of the returned string including the trail. That feels really weird to me. I come from the Twig world, and there it works like you would expect: truncate to maximum size, and append the trail, see: http://twig-extensions.readthedocs.io/en/latest/text.html#truncating-text

Was this intended?

**Comment by markbates** [comment]
Yes; that’s intended. “How many characters of your string would you like to display before cutting it off”.
