### ISSUE TITLE
How to turn off automatic html escaping?

### ISSUE THREAD

**Issue by rooty123** [gobuffalo/plush#62]
I found that plush escapes html in variables automatically. How can I switch it off?

**Comment by markbates** [comment]
`string` types gets escaped for safety. `template.HTML` types don’t. Use the correct types to get escaping or not. There is also a `safe`, or maybe it’s `raw`, helper that will mark a `string` as safe

**Comment by rooty123** [comment]
Thanks it works with `raw` helper. By the way it's not documented in README.

**Comment by JefMasereel** [comment]
Thanks, this clarifies things. 'raw' is not listed under the builtin helpers on your documentation though, maybe worth adding some documentation there? https://gobuffalo.io/documentation/frontend-layer/helpers/

Basic code reference: use the 'raw' builtin helper in your template to render received string without HTML escaping.

```main.go
package main

import (
	"fmt"
	"github.com/gobuffalo/plush"
	"log"
)

func main() {
	template := `
blabla

<%= raw(trustedContent) %>

blabla`

	ctx := plush.NewContext()
	ctx.Set("trustedContent", `{"hello;world&a;b","c;d"}`)

	s, err := plush.Render(template, ctx)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Print(s)
	return
}
```

If this does not cover your needs, consider building a custom helper
https://gobuffalo.io/documentation/frontend-layer/custom-helpers/
