### ISSUE TITLE
IDE Support

### ISSUE THREAD

**Issue by paulZzhang** [gobuffalo/plush#63]
IDE goland plugin for the template engine. eg [twig template engine](http://plugins.jetbrains.com/plugin/7303-twig-support)

**Comment by valasek** [comment]
Hi Paul,

can you rewrite your issue as a story? Some hints:

- Please **be** as **specific** as possible. E.g. how exactly it would help e.g. to have higher dev productivity. How specifically the feature should be integrated. Add links to examples if possible.
- Add **factual context**.  E.g. which IDEs do you propose and why those.

**Comment by paulZzhang** [comment]
@valasek I need IDE goland plugin for the template engine. eg twig template engine

**Comment by paulZzhang** [comment]
[vscode plugin](https://github.com/hasit/vscode-plush)

**Comment by robbyoconnor** [comment]
@paulZzhang here is the [documentation](https://www.jetbrains.com/help/go/settings-file-and-code-templates.html). I stopped using IDEs a long time ago when I realized I could have more control by using vim/emacs.

**Comment by robbyoconnor** [comment]
@paulZzhang don't close this -- it's not resolved yet! 

I was saying to write the plugin...

**Comment by paulZzhang** [comment]
The format is very bad for VScode editor with the template engine plush.
Solution:
` "html.format.contentUnformatted": "%, %="`

**Comment by josephtaylor** [comment]
It would be really nice to have a GoLand plugin that:

1. parses the templates and recognizes syntax errors.
2. provides syntax highlighting.
3. resolves/auto-completes variables and keywords.

**Comment by galaczi** [comment]
While OP's post was not very detailed, I would also like to see a VSCode plugin for plush. I understand some people like to use VIM, but that doesn't change the fact that the vast majority of people still use IDEs. Among web developers VSCode is the most used. 

As joseph wrote, the main features would be:

- parses the templates and recognizes syntax errors.
- provides syntax highlighting.
- resolves/auto-completes variables and keywords.

There are two VSCode plugins currently. Both are abandoned and have bugs and limited features.

**Comment by robbyoconnor** [comment]
Why not write one, folks? If you want it, make it happen. This is the beautiful thing about Open Source.

**Comment by galaczi** [comment]
> Why not write one, folks? If you want it, make it happen. This is the beautiful thing about Open Source.

I didn't even use the framework yet and without templating support in any IDE, I won't be able to. Hence why I (and others) ask the community. It's not an entirely selfish request. If the framework authors want wide adoption, it's essential in my opinion.

**Comment by robbyoconnor** [comment]
@galaczi was definitely not accusing you of being selfish but rather encouraging you to contribute. No need to be sorry if you're not able to.
