### ISSUE TITLE
How to use GroupBy?

### ISSUE THREAD

**Issue by vizcay** [gobuffalo/plush#70]
Hi, sorry but I wasn't able to locate the docs for that (tried at https://godoc.org/github.com/gobuffalo/buffalo and also at the README but no examples).

I need to pair a slice into 2 per row pairs.

Ruby developer, learning Go and Buffalo at the same time..

Thanks!

**Comment by markbates** [comment]
That helper take a int (how many groups you want) and a slice to divide up.

https://github.com/gobuffalo/plush/blob/master/iterators_test.go

The tests explain it a bit clearer; but we need more docs there.

<%= form_for(contact, {action: "/contact"}) { %>
<%= f.InputTag("Name") %>
<%= f.InputTag("Email") %>
<%= f.InputTag("Company") %>
<%= f.TextArea("Description", {rows: 10, label: "Please let us what you are looking for in regards to training."}) %>
<label>Please check the topics that are of interest for you.</label>
<div class="row">
   <%= for (g) in groupBy(2, interests) { %>
     <div class="col-md-6">
       <%= for (i, n) in g { %>
         <%= f.CheckboxTag("Interests", {name: "Interests["+n+"]", value: contact.Interests[n], label: n, checked: n}) %>
       <% } %>
     </div>
   <% } %>
</div>
<button type="submit" class="btn btn-primary">Contact Gopher Guides</button>
<% } %>

That’s a real world example. It takes the slice and breaks it into 2 so I can make two nice columns in HTML

**Comment by sio4** [comment]
Closing. It seems like it's an answered question.
