### ISSUE TITLE
contentFor/contentOf not working as documented?

### ISSUE THREAD

**Issue by pharrisee** [gobuffalo/plush#71]
I have a layout template which includes:

```
    <% contentFor("title"){%>
        <title><%=title%></title>
    <%} %>
```

and a page template which includes:

`<%= contentOf("title", {"title":"Admin Home"} ) %>`

Which according to the current documentation is correct, but I get an error when rendering the page:

index.html: line 1: missing contentOf block: title

Is the contentOf supposed to have a block? i.e. is it supposed to be more like the following?

```
<%= contentOf("title", {"title":"Admin Home"} ) { %>
<% } %>
```

**Comment by markbates** [comment]
contentOf requires a block if there is no content for that key already stored.

In your case you’re contentFor in the layout which gets executed after the inner template, so your contentFor isn’t being called first.

Thanks.

-----------
Mark Bates

**Comment by pharrisee** [comment]
So is there any way of achieving what I'm suggesting, i.e. create a 'placeholder' in the layout which is filled by the page template?

At the moment I'm using contentFor and contentOf like this:

layout:
```
    <% contentFor("title"){ %>
    <% } %>
```

page:
```
<%= contentOf("title" ) { %>
<title>Cardiff University Software</title>
<% } %>
```

which isn't too bad, but seems to be a bit reversed according to the documentation.

**Comment by markbates** [comment]
Yes, flip the calls. contentFor sets and contentOf retrieves.

-----------
Mark Bates
