### ISSUE TITLE
template.Exec should not erase error type

### ISSUE THREAD

**Issue by mh-cbon** [gobuffalo/plush#96]
given a template such as

```
<%= fn() %>
```

a context such as

```
type aSpecificErrorType struct { error }
ctx.Set("fn", func() error { return aSpecificErrorType{} })
```

the template.Exec method should not wrap the error in a way that erase its type.

Such deletion happens in statements like `errors.WithStack(errors.Errorf("line %d: %s", s.T().LineNumber, err))`

I would like that the error is wrapped using errors.Wraper methods so i can use `err = errors.Cause(err)` to retrieve the underlying error i m interesting in.

**Comment by paganotoni** [comment]
This one should be solved in #141.
